<div class="<?php echo $this->getClassname()?>" style="<?php echo $this->getInlinestyle()?>" data-seconds-left=<?php echo $this->getSecondsLeft()?>>
<?php if ($this->getDaysLeft() > 0): ?>
    <span class="days"><?php echo $this->getDaysLeft()." day(s)&nbsp;"; ?></span>
<?php endif ?>
</div>
<script type="text/javascript">
    // strt flip timer
    // jQuery('.<?php echo TM_CountdownTimer_Block_Timer_Flip::getTimerBaseClass() ?>').each(
    //     function (index, value) {
    //         jQuery(this).FlipClock(
    //             jQuery(this).attr('data-seconds-left'),
    //             {
    //                 clockFace: jQuery(this).attr('data-flipface'),
    //                 countdown: true
    //             }
    //         )
    //     }
    // );
    // start simple timer
    // jQuery('.<?php echo TM_CountdownTimer_Block_Timer_Simple::getTimerBaseClass() ?>').startTimer();
</script>