<?php
	$_secondsLeft = $this->getSecondsLeft();
	$_daysLeft = 0;
	if ($this->getDisplayDays()) {
		$_daysLeft = $this->getDaysLeft();
		$_secondsLeft = $_secondsLeft - $_daysLeft * (24*60*60);
	}
?>
<div class="<?php echo $this->getClassname()?>" style="<?php echo $this->getInlinestyle()?>" data-seconds-left=<?php echo $_secondsLeft?>>
<?php if ($_daysLeft > 0 ): ?>
    <span class="days"><?php echo $_daysLeft." ".Mage::helper('tm_countdowntimer')->__('day(s)'); ?></span>
<?php endif ?>
</div>
