<script type="text/javascript">
  function setAttributeSecondsLeft(htmlObj) {
    if (htmlObj.hasAttribute('data-end-datetime-utc')) {
      var secondsLeft = parseInt(htmlObj.getAttribute('data-end-datetime-utc'));
      secondsLeft -= Math.floor(Date.now() / 1000);
      if (secondsLeft < 0) {secondsLeft = 0};
      htmlObj.setAttribute('data-seconds-left', secondsLeft);
    };
  }
  function setDaysForSimpleTimer(htmlObj) {
    if (!htmlObj.hasAttribute('data-display-days')) { return; };
    var secondsLeft = parseInt(htmlObj.getAttribute('data-seconds-left'));
    var numberOfDays = Math.floor( secondsLeft / ( 24 * 60 * 60 ) );
    if (numberOfDays > 0) {
      jQuery(htmlObj).find('.days').text(numberOfDays.toString() + ' ' + Translator.translate('day(s)'));
      secondsLeft -= numberOfDays * 24 * 60 * 60;
      htmlObj.setAttribute('data-seconds-left', secondsLeft);
    } else {
      jQuery(htmlObj).find('.days').text('');
    };
  }
  var timerSimpleClass = '.<?php echo str_replace(" ", ".", TM_CountdownTimer_Block_Timer_Simple::getTimerBaseClass()) ?>';
  var timerFlipClass = '.<?php echo str_replace(" ", ".", TM_CountdownTimer_Block_Timer_Flip::getTimerBaseClass()) ?>';
  var localeName = '<?php echo Mage::app()->getLocale()->getLocaleCode();?>';
  // translations for flipclock labels
  FlipClock.Lang[localeName] = {
    'years' : Translator.translate('Years'),
    'months' : Translator.translate('Months'),
    'days' : Translator.translate('Days'),
    'hours' : Translator.translate('Hours'),
    'minutes' : Translator.translate('Minutes'),
    'seconds' : Translator.translate('Seconds')
  };
  // start flip timer
  jQuery(timerFlipClass).each(
    function (index, htmlObj) {
      setAttributeSecondsLeft(htmlObj);
      jQuery(htmlObj).FlipClock(
        htmlObj.getAttribute('data-seconds-left'),
        {
          clockFace: htmlObj.getAttribute('data-flipface'),
          countdown: true,
          language: localeName
        }
      );
    }
  ).removeClass('not-started');
  // start simple timer
  jQuery(timerSimpleClass).each(
    function (index, htmlObj) {
      setAttributeSecondsLeft(htmlObj);
      setDaysForSimpleTimer(htmlObj);
    }
    ).startTimer().removeClass('not-started');
</script>
